# Generated by Django 4.2.27 on 2026-01-24 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Camera",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название камеры"),
                ),
                ("price", models.IntegerField(verbose_name="Цена камеры")),
                (
                    "picture",
                    models.ImageField(upload_to="", verbose_name="Фото камеры"),
                ),
            ],
        ),
    ]
