# Generated by Django 4.2.27 on 2026-01-24 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_camera_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="camera",
            options={"verbose_name": "Камера", "verbose_name_plural": "Камеры"},
        ),
        migrations.AddField(
            model_name="camera",
            name="connection_type",
            field=models.CharField(default="Провод", max_length=10),
        ),
        migrations.AddField(
            model_name="camera",
            name="has_dynamic",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="camera",
            name="has_micro",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="camera",
            name="lens",
            field=models.CharField(default="Zoom", max_length=15),
        ),
        migrations.AddField(
            model_name="camera",
            name="night_vision_longesity",
            field=models.IntegerField(
                default=30, verbose_name="Дальность ночного видения"
            ),
        ),
        migrations.AddField(
            model_name="camera",
            name="night_vision_technology",
            field=models.CharField(default="Color", max_length=6),
        ),
        migrations.AddField(
            model_name="camera",
            name="resolution",
            field=models.IntegerField(default=2, verbose_name="Разрешение"),
        ),
    ]
