# Generated by Django 4.2.27 on 2026-01-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_camera_options_camera_connection_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="camera",
            name="night_vision_longesity",
        ),
        migrations.AddField(
            model_name="camera",
            name="analytics",
            field=models.CharField(default="Человек", max_length=30),
        ),
        migrations.AddField(
            model_name="camera",
            name="type",
            field=models.CharField(default="Купольная", max_length=10),
        ),
    ]
