# Generated by Django 4.2.27 on 2026-01-28 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_remove_camera_night_vision_longesity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="camera",
            name="picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="camera_images/",
                verbose_name="Фото камеры",
            ),
        ),
    ]
