# Generated by Django 4.2.27 on 2026-01-28 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_camera_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="camera",
            name="picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="main/static/main/img/camera_images",
                verbose_name="Фото камеры",
            ),
        ),
    ]
